# frozen_string_literal: true

module Api
  module V1
    class AuthController < BaseController
      skip_before_action :authenticate_user!, only: [:login, :register]

      # POST /api/v1/auth/login
      def login
        user = User.find_by(email: login_params[:email])

        if user&.valid_password?(login_params[:password])
          # Generate JWT token (handled by devise-jwt)
          token = generate_jwt_token(user)
          
          render_success(
            {
              user: user_response(user),
              token: token
            },
            message: 'Login successful'
          )
        else
          render_error(
            'Invalid email or password',
            status: :unauthorized,
            code: 'INVALID_CREDENTIALS'
          )
        end
      end

      # POST /api/v1/auth/register
      def register
        user = User.new(register_params)

        if user.save
          token = generate_jwt_token(user)
          
          render_success(
            {
              user: user_response(user),
              token: token
            },
            status: :created,
            message: 'Registration successful'
          )
        else
          render_error(
            'Registration failed',
            status: :unprocessable_entity,
            code: 'REGISTRATION_FAILED',
            errors: user.errors.as_json
          )
        end
      end

      # DELETE /api/v1/auth/logout
      def logout
        # JWT is automatically added to denylist by devise-jwt
        render_success(
          {},
          message: 'Logout successful'
        )
      end

      # GET /api/v1/auth/me
      def me
        render_success(
          { user: user_response(current_user) },
          message: 'Current user retrieved'
        )
      end

      private

      def login_params
        params.require(:auth).permit(:email, :password)
      end

      def register_params
        params.require(:auth).permit(
          :email,
          :password,
          :password_confirmation,
          :full_name,
          :phone_number,
          :role
        )
      end

      def generate_jwt_token(user)
        # JWT token is automatically generated by devise-jwt
        # We need to manually generate it here for the response
        payload = {
          sub: user.id,
          scp: 'user',
          jti: user.jti,
          exp: 1.hour.from_now.to_i
        }
        
        JWT.encode(
          payload,
          Rails.application.credentials.devise_jwt_secret_key || ENV['DEVISE_JWT_SECRET_KEY'],
          'HS256'
        )
      end

      def user_response(user)
        {
          id: user.id,
          email: user.email,
          full_name: user.full_name,
          role: user.role,
          phone_number: user.phone_number,
          is_qualified_instructor: user.is_qualified_instructor,
          created_at: user.created_at
        }
      end
    end
  end
end
